### ISSUE TITLE
hi！bro. ，after run your traning code , I got the following errors

### ISSUE THREAD

**Issue by Castile** [carrierlxk/COSNet#18]
Traceback (most recent call last):
  File "train_iteration_conf.py", line 450, in <module>
    main()
  File "train_iteration_conf.py", line 375, in main
    lr=args.learning_rate, momentum=args.momentum, weight_decay=args.weight_decay)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\optim\sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\optim\optimizer.py", line 50, in __init__
    self.add_param_group(param_group)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\optim\optimizer.py", line 193, in add_param_group
    param_group['params'] = list(params)
  File "train_iteration_conf.py", line 226, in get_10x_lr_params
    b.append(model.main_classifier.parameters())
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'

**Comment by Thiruvavinan** [comment]
please help ! Even I am facing the same issue (fresh to Torch :( )

**Comment by carrierlxk** [comment]
I guess this is because of the system. My codes run at ubuntu system, I have never run my codes on windows, so I can not handle this issue.

**Comment by Castile** [comment]
b.append(model.encoder.main_classifier.parameters())

**Comment by liuuuuuuxuesong** [comment]
main_classifier, main_classifier1, and main_classifier2 are the same in CoattentionModel, for single or multiple gpus.

**Comment by averyjuuu** [comment]
> main_classifier、main_classifier1 和 main_classifier2 在 CoattentionModel 中是相同的，对于单个或多个 gpus。

您好，这个问题要怎样修改呢，没找到要怎么修改

**Comment by averyjuuu** [comment]
> 

您好，这个问题您是怎么解决的
