### ISSUE TITLE
请问测试数据的文件夹的格式是什么？

### ISSUE THREAD

**Issue by Castile** [carrierlxk/COSNet#6]
(pytorch) F:\jetbrains\pycharm\COSNet>python test_coattention_conf.py --dataset davis
=====> Configure dataset and model
Namespace(batch_size=1, corp_size=(473, 473), cuda=True, data_dir='./DAVIS', data_list='./DAVIS/val_seq.txt', dataset='davis', gpus='0', ignore_label=255, img_mean=array([ 104.00698853,  116.66876984,  122.67891693], dtype=float32), input_size='473,473', maxEpoches=15, num_classes=2, restore_from='./co_attention.pth', sample_range=2, save_segimage=True, seg_save_dir='./result/test/davis_iteration_conf', seq_name='bmx-bumps', snapshot_dir='./snapshots/davis_iteration/', use_crf='True', vis_save_dir='./result/test/davis_vis')
======> test set size: 50
Traceback (most recent call last):
  File "test_coattention_conf.py", line 279, in <module>
    main()
  File "test_coattention_conf.py", line 168, in main
    for index, batch in enumerate(testloader):
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "F:\jetbrains\pycharm\COSNet\dataloaders\PairwiseImg_test.py", line 119, in __getitem__
    my_index = self.Index[seq_name1]
**KeyError: '480p'**

出现了keyError
我使用的是davis数据集。val_seqs.txt  是存放什么鸭？

**Comment by carrierlxk** [comment]
val_seqs.txt stores the video name of davis-2016:
blackswan
bmx-trees
breakdance
camel
car-roundabout
car-shadow
cows
dance-twirl
dog
drift-chicane
drift-straight
goat
horsejump-high
kite-surf
libby
motocross-jump
paragliding-launch
parkour
scooter-black
soapbox

**Comment by Castile** [comment]
谢谢你，上面问题已经解决，但是使用您的模型文件测试blackswan的时候：
test_coattention_conf.py:184: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  output = model(Variable(target, volatile=True).cuda(),Variable(search_im, volatile=True).cuda())
D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "test_coattention_conf.py", line 280, in <module>
    main()
  File "test_coattention_conf.py", line 184, in main
    output = model(Variable(target, volatile=True).cuda(),Variable(search_im, volatile=True).cuda())
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\jetbrains\pycharm\COSNet\deeplab\siamese_model_conf.py", line 256, in forward
    exemplar, temp = self.encoder(input1)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\jetbrains\pycharm\COSNet\deeplab\siamese_model_conf.py", line 212, in forward
    x = self.layer3(x)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\jetbrains\pycharm\COSNet\deeplab\siamese_model_conf.py", line 82, in forward
    out = self.bn3(out)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "D:\Program Files\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 14.13 MiB (GPU 0; 6.00 GiB total capacity; 4.58 GiB already allocated; 5.64 MiB free; 18.73 MiB cached)

显示内存溢出，测试模型需要的显存要多大合适呀，我的是GTX1060， 6G 显存

**Comment by Castile** [comment]
我加了with torch.no_grad()：好像就可以运行了。谢谢！！！
